#!/bin/sh

#DEBHELPER#

deluser --quiet weatherstation dailout 2>/dev/null || true

if ( [ ! -e /etc/weatherstation/chart.conf ] && [ ! -e /etc/weatherstation/checksensor.conf ] && [ ! -e /etc/weatherstation/frontend.conf ] ); then
	if getent passwd weatherstation >/dev/null 2>&1; then
		echo -n "delete user weatherstation ... "
	        deluser --quiet weatherstation  2>/dev/null || true
		echo "done"
	fi
fi
