Document: weatherstation
Title: Debian weatherstation Manual
Author: <insert document author here>
Abstract: This manual describes what weatherstation is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/weatherstation/weatherstation.sgml.gz

Format: postscript
Files: /usr/share/doc/weatherstation/weatherstation.ps.gz

Format: text
Files: /usr/share/doc/weatherstation/weatherstation.text.gz

Format: HTML
Index: /usr/share/doc/weatherstation/html/index.html
Files: /usr/share/doc/weatherstation/html/*.html

  
