#!/bin/sh
# weatherstation-frontend postinst

echo ""
echo "####################################################"
echo "#  Achtung:                                        #"
echo "#  Bitte lesen Sie die Anleitung zur weiteren      #"
echo "#  Installation unter:                             #"
echo "#  /usr/share/doc/weatherstation-frontend/reademe  #"
echo "#  nach!                                           #"
echo "####################################################"
echo ""

#DEBHELPER#
